# ./docker-compose.yml ,  192.168.88.46:6021

version: '3'

services:

  web:
    #image: php:7.2.2-apache
    build: ./php
    image: dkr378php8
    restart: always
    container_name: dkr378php8
    #  first load the 'db' service 
    depends_on:
      - db
    env_file:
      - env
    volumes:
      - /var/www/html/:/var/www/html/
      
      # - ./dkr378php6/php/xtra.php.ini:/etc/php5/apache2/conf.d/custom.php.ini
      # https://stackoverflow.com/questions/41691584/docker-compose-wont-volume-my-php-ini-file
      # - ./php/:/var/www/html/
      # - ./dkr378php6/php:/usr/local/etc/php
      # - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php5/fpm/conf.d/99-overrides.ini
      
    ports:
      - "6021:80"
    stdin_open: true
    tty: true
    networks:
      - one
    # make 'db' a known service/host inside of 'web'
    # use this to make a mysql connection to host 'db'
    # https://www.goodbytes.be/blog/article/docker-a-simple-example-for-a-php-mysql-setup
    #links:
    #  - db
    
  db:
    image: mysql:5.7
    #build: ./mysql
    #image: dkr378php9mysq
    restart: always
    container_name: dkr378php9mysq
    env_file:
      - env
    # environment:
      # MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: test
      # MYSQL_USER: dev
      # MYSQL_PASSWORD: dev
    ports:
      - "6022:3306"
    volumes:
      - /var/aa/mysql2/:/var/lib/mysql/
    networks:
      - one

networks:
  one:
    